/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication4;

/**
 *
 * @author PC RPL - R1
 */
public class modul5 extends javax.swing.JFrame {

    /**
     * Creates new form modul4
     */
    public modul5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        makanan = new javax.swing.JLabel();
        cbGeprek = new javax.swing.JCheckBox();
        cbBakar = new javax.swing.JCheckBox();
        cbGoreng = new javax.swing.JCheckBox();
        minuman = new javax.swing.JLabel();
        cbTeh = new javax.swing.JCheckBox();
        cbKopi = new javax.swing.JCheckBox();
        JbClear = new javax.swing.JButton();
        JbProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResume = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nama.setText("Nama");

        alamat.setText("Alamat");

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });

        tfalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfalamatActionPerformed(evt);
            }
        });

        makanan.setText("Makanan");

        cbGeprek.setText("Ayam Geprek");
        cbGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeprekActionPerformed(evt);
            }
        });

        cbBakar.setText("Ayam Bakar");
        cbBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBakarActionPerformed(evt);
            }
        });

        cbGoreng.setText("Ayam Goreng");
        cbGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGorengActionPerformed(evt);
            }
        });

        minuman.setText("Minuman");

        cbTeh.setText("Teh Hangat");
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        cbKopi.setText("Kopi");
        cbKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopiActionPerformed(evt);
            }
        });

        JbClear.setText("Clear");
        JbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbClearActionPerformed(evt);
            }
        });

        JbProses.setText("Proses");
        JbProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbProsesActionPerformed(evt);
            }
        });

        areaResume.setColumns(20);
        areaResume.setRows(5);
        jScrollPane1.setViewportView(areaResume);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(cbKopi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(minuman)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbTeh)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(makanan)
                                    .addComponent(alamat)
                                    .addComponent(nama))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfalamat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGeprek)
                                            .addComponent(cbBakar)
                                            .addComponent(cbGoreng))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(JbClear)
                        .addGap(55, 55, 55)
                        .addComponent(JbProses)
                        .addGap(15, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makanan)
                    .addComponent(cbGeprek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBakar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGoreng)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTeh)
                    .addComponent(minuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbKopi)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbClear)
                    .addComponent(JbProses))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void cbBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBakarActionPerformed

    private void cbGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGorengActionPerformed

    private void JbProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbProsesActionPerformed
        if (cbGeprek.isSelected()){ 
daftarHoby +=cbGeprek.getText()+""; 
}if (cbBakar.isSelected()){ 
daftarHoby +=cbBakar.getText()+""; 
}if (cbGoreng.isSelected()){ 
daftarHoby +=cbGoreng.getText()+""; 
}if (cbTeh.isSelected()){ 
daftarHoby +=cbTeh.getText()+""; 
}if (cbKopi.isSelected()){ 
daftarHoby +=cbKopi.getText()+""; 
};
    }//GEN-LAST:event_JbProsesActionPerformed

    private void cbGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeprekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGeprekActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTehActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKopiActionPerformed

    private void JbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbClearActionPerformed
        areaResume.setTex(““)
    }//GEN-LAST:event_JbClearActionPerformed

    private void tfalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfalamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbClear;
    private javax.swing.JButton JbProses;
    private javax.swing.JLabel alamat;
    private javax.swing.JTextArea areaResume;
    private javax.swing.JCheckBox cbBakar;
    private javax.swing.JCheckBox cbGeprek;
    private javax.swing.JCheckBox cbGoreng;
    private javax.swing.JCheckBox cbKopi;
    private javax.swing.JCheckBox cbTeh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel makanan;
    private javax.swing.JLabel minuman;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables
}
